### ISSUE TITLE
esdoc build error

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#32]
Latest merge generated a bug when generating documentation. The error description follows:

TypeError: Cannot read property 'length' of undefined
    at LintDocBuilder._showResult (C:\Users\rafael.tavares\projects-mp\github\inLoco-2.0\node_modules\esdoc\out\src\Publisher\Builder\LintDocBuilder.js:150:64)
    at LintDocBuilder.exec (C:\Users\rafael.tavares\projects-mp\github\inLoco-2.0\node_modules\esdoc\out\src\Publisher\Builder\LintDocBuilder.js:52:10)
    at publish (C:\Users\rafael.tavares\projects-mp\github\inLoco-2.0\node_modules\esdoc\out\src\Publisher\publish.js:177:48)
    at Function.generate (C:\Users\rafael.tavares\projects-mp\github\inLoco-2.0\node_modules\esdoc\out\src\ESDoc.js:137:7)
    at ESDocCLI.exec (C:\Users\rafael.tavares\projects-mp\github\inLoco-2.0\node_modules\esdoc\out\src\ESDocCLI.js:75:23)
    at Object.<anonymous> (C:\Users\rafael.tavares\projects-mp\github\inLoco-2.0\node_modules\esdoc\out\src\ESDocCLI.js:186:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by rlage** [comment]
I found out that there were an extra @param description on the geoServerXmlReducer, so that is causing the problem.

**Comment by rlage** [comment]
waiting PR review from @pedromarins
